topic:
  name: users
  partitions-num: 3
  replication-factor: 1
server:
  port: 9080
spring:
  kafka:
    bootstrap-servers:
      - pkc-ymrq7.us-east-2.aws.confluent.cloud:9092  # <1>
    properties:
      # CCloud broker connection parameters
      ssl.endpoint.identification.algorithm: https
      sasl.mechanism: PLAIN
      request.timeout.ms: 20000
      retry.backoff.ms: 500
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule   required username='SYNBWX6GH6LM5PL6'   password='BmiTW8ZJbdfpqe1NeiJFA0+0xz0JbXtbeniM+eHYigxKArRP6cRDE6z+pKcIgyM9';  # <2>
      security.protocol: SASL_SSL

      # CCloud Schema Registry Connection parameter
      schema.registry.url: https://psrc-68gz8.us-east-2.aws.confluent.cloud  # <3>
      basic.auth.credentials.source: USER_INFO  # <4>
      schema.registry.basic.auth.user.info: 65F6YLYZBQFSV5CJ:X9rIo/bRfPM+lkGuQLWLTDsdApyj6PLknqDNvdlmR606aAa7nmIvxCJcCUnDZ3HL # <5>
    consumer:
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    template:
      default-topic:
logging:
  level:
    root: info
