topic:
  name: users
  partitions-num: 3
  replication-factor: 1
server:
  port: 9080
spring:
  kafka:
    bootstrap-server: {server_url}
    bootstrap-servers:
      - {server_url}
    properties:
      # CCloud broker connection parameters
      bootstrap:
        servers: {server_url}
      ssl.endpoint.identification.algorithm: https
      sasl.mechanism: PLAIN
      request.timeout.ms: 45000
      retry.backoff.ms: 500
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule   required username='{user_name}'   password='{password}';
      security.protocol: SASL_SSL

      # CCloud Schema Registry Connection parameter
      schema.registry.url: {scema_registry_url}
      basic:
        auth:
          user.info: {registry_user_auth_info}
          credentials.source: USER_INFO
      specific.avro.reader: true
    consumer:
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    template:
      default-topic:
logging:
  level:
    root: info
